create table users (
ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE 
    PRIMARY KEY NOT NULL,
    name varchar2(50) not null,
    lastName varchar(50) not null,
    phoneNumber varchar2(13) not null,
    password varchar2(100) not null,
    createDate TIMESTAMP not null,
    email varchar2(100) not null
);
create table otp (
     ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE 
    PRIMARY KEY NOT NULL,
    createDate TIMESTAMP not null,
    otp varchar2(6) not null,
    id_users number not null,
    foreign key (id_users) references users(id)
);
create table statusOtp(
     ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE 
    PRIMARY KEY NOT NULL,
    sent varchar2(20)not null,
    deleted varchar2(20)not null,
    verified varchar2(20)not null,
    id_otp number not null,
    foreign key (id_otp) references otp(id) 
);
create table comunication(
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE 
    PRIMARY KEY NOT NULL,
    sms varchar2(100),
    email varchar(100),
    id_otp number not null,
    foreign key (id_otp) references otp(id)
);
create table account(
     ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE 
    PRIMARY KEY NOT NULL,
    originNumber varchar2(13) not null,
    balance number not null,
    createDate TIMESTAMP not null,
    id_users number not null,
    foreign key (id_users) references users(id)
);
create table transactions(
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE 
    PRIMARY KEY NOT NULL,
    createDate TIMESTAMP not null,
    originNumber varchar2(15),
    destinationAccount varchar2(50),
    amount number not null,
    reference varchar2(10),
    description varchar2(100),
    id_account number not null,
    id_statusTransactions number not null,
    foreign key (id_account) references account (id)
);
create table statusTransactions(
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE 
    PRIMARY KEY NOT NULL,
    sent varchar2(20),
    retired varchar2(20),
    cancelled varchar2(20),
    id_transactions number not null,
    foreign key (id_transactions) references transactions(id)
);
create table pocket(
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE 
    PRIMARY KEY NOT NULL,
    name varchar2(50) not null,
    createDate TIMESTAMP not null,
    amount varchar2(50) not null,
    id_account number not null,
    foreign key (id_account) references account(id)
);
