create table users (
ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE 
    PRIMARY KEY NOT NULL,
    name varchar2(50) not null,
    lastName varchar(50) not null,
    phoneNumber varchar2(13) not null,
    password varchar2(100) not null,
    createDate TIMESTAMP not null,
    email varchar2(100) not null
);
create table otp (
     ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE 
    PRIMARY KEY NOT NULL,
    createDate TIMESTAMP not null,
    otp varchar2(6) not null,
    comunication_id number not null,
    statusOtp_id number not null,
    user_id number not null,
    foreign key (user_id) references users(id),
    foreign key (statusOtp_id) references statusOtp(id),
    foreign key (comunication_id)references comunication(id)
);
create table statusOtp(
     ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE 
    PRIMARY KEY NOT NULL,
    sent varchar2(20)not null,
    deleted varchar2(20)not null,
    verified varchar2(20)not null
);
create table comunication(
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE 
    PRIMARY KEY NOT NULL,
    sms varchar2(100),
    email varchar(100)
);
create table account(
     ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE 
    PRIMARY KEY NOT NULL,
    originNumber varchar2(13) not null,
    balance number not null,
    createDate TIMESTAMP not null,
    user_id number not null,
    foreign key (user_id) references users(id)
);
create table transactions(
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE 
    PRIMARY KEY NOT NULL,
    createDate TIMESTAMP not null,
    originNumber varchar2(15),
    destinationAccount varchar2(50),
    amount number not null,
    reference varchar2(10),
    description varchar2(100),
    account_id number not null,
    statusTransactions_id number not null,
    foreign key (account_id) references account (id), 
    foreign key (statusTransactions_id) references transactions(id)
);
create table statusTransactions(
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE 
    PRIMARY KEY NOT NULL,
    sent varchar2(20),
    retired varchar2(20),
    cancelled varchar2(20)
);
create table pocket(
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE 
    PRIMARY KEY NOT NULL,
    name varchar2(50) not null,
    createDate TIMESTAMP not null,
    amount varchar2(50) not null,
    account_id number not null,
    foreign key (account_id) references account(id)
);